### ISSUE TITLE
Not showing in „Share with“ menu

### ISSUE THREAD

**Issue by poochie89** [marchellodev/sharik#102]
Sharik 3.0 is not showing up on iOS when using the system share menu to share a text or a picture

**Comment by marchellodev** [comment]
I have just reinstalled the app from the App Store, and everything seems to work properly. At least with Files, Photos, and 'Share' option when selecting text

![image](https://user-images.githubusercontent.com/61112084/130363353-07483f74-0757-4730-a08d-2ea93795c698.png)
![image](https://user-images.githubusercontent.com/61112084/130363355-4215720c-b29d-4745-af59-43e89136be13.jpeg)

**Comment by poochie89** [comment]
Its working after updating the OS to the latest version
