### ISSUE TITLE
I found sharik on google play store, Is it official?

### ISSUE THREAD

**Issue by 312k** [marchellodev/sharik#109]
I found sharik on google play store.
But I felt weird because app icon is different from github's.
Is it official app?
[sharik](https://play.google.com/store/apps/details?id=dev.alkhalaf.sharik)
This is the play store links.

**Comment by marchellodev** [comment]
No, this one is a fork, I think based on v2.5. So it's pretty old :) But it has a few design changes and new languages

Actually, my account got banned from the Play Store (for some unknown weird reason lmao), so now you can only install it via directly downloading apk or using f-droid.

I hope Play Store is going to allow me to make Sharik available on Play Store from another developer account (not attached to me)
