### ISSUE TITLE
Microsoft Store version is outdated

### ISSUE THREAD

**Issue by itsmeboy0** [marchellodev/sharik#117]
I installed Sharik from the Microsoft Store, only to find out that it is still v2.5 and way outdated.

**Comment by marchellodev** [comment]
Thanks for reporting this! I will try to fix this soon :)

**Comment by marchellodev** [comment]
I'll let you know when the update is live.

Thanks again!

![image](https://user-images.githubusercontent.com/61112084/140274916-5ff26350-bae6-4983-9693-1ef50ebb2e02.png)

**Comment by marchellodev** [comment]
The app should be updated now. Thanks @itsmeboy0
