### ISSUE TITLE
QRCODE

### ISSUE THREAD

**Issue by celiasrox** [marchellodev/sharik#22]
As the tittle suggest, I think a great feature would be to generate QR CODE instead of having to manually type the address. Besides that the app is really great, tks for making it.

**Comment by marchellodev** [comment]
Thanks for the suggestion! Seems like a really great idea!

**Comment by dCo3lh0** [comment]
i could add some suggestions here to that same feature, options like "show address in QRCode", "Save QRCode image file", so people can share into messengers like whatsapp, telegram (easier than an option that "Shares QRCode in" option). A QRCode Scanner that scans the QRCode and following opens in the default browser application, i think thats that.

**Comment by marchellodev** [comment]
Cool, thanks!

**Comment by marchellodev** [comment]
This is implemented in Sharik v3 https://github.com/marchellodev/sharik/issues/63 !

Thank you for the suggestion, I'll close this issue for now.
