### ISSUE TITLE
Add support to the Pinephone

### ISSUE THREAD

**Issue by Kohoshi12** [marchellodev/sharik#23]
Pinephone is the Arm-based touchphone developed by Pine64 with Linux in mind, the software is made almost entirely by the community. Would be cool to use this program with linux phones.

**Comment by marchellodev** [comment]
Isn't this just Linux on arm architecture?

**Comment by Kohoshi12** [comment]
Yes, but with a smaller and touch function screen. The pinephone defines what will work on other devices as well, even though it's not perfect.

**Comment by marchellodev** [comment]
@Kohoshi12 Are you aware if I can run it in vmware/virtualbox? I have found only iso of kde neon mobile, but I could not fully install it as it is very buggy

**Comment by Kohoshi12** [comment]
Pinephone has a lot of operating systems such as Arch Arm, Mobian (Debian), Postmarketos, Manjaro Arm. I'm sorry, but I'm not a coder. You can search for support on the forums of Pine64 or on the Matrix room #pinephone:matrix.org. I wish you luck.

**Comment by boingo-00** [comment]
UI is ready, that should be fine on phones, the only thing it needed is ARM build

![Screenshot_20210228_102518](https://user-images.githubusercontent.com/10793815/109410890-45125880-79af-11eb-8279-0bc4341ff808.png)

**Comment by marchellodev** [comment]
Yep, but it seems like Flutter doesn't support linux arm architecture yet. So I guess we'll just have to wait.

https://github.com/flutter/flutter/issues/60678

**Comment by marchellodev** [comment]
Yeah, it seems like Flutter does not yet support aarch64 builds (the architecture pinephone runs on)
