### ISSUE TITLE
2 minor corrections for the linux .desktop file

### ISSUE THREAD

**Issue by pitsi** [marchellodev/sharik#27]
I noticed that the menu shortcut for sharik is listed under "other" group and it has the generic executable icon instead of the one you provide. Both these issues can be resolved with a bit of editing on the .desktop file.

For the icon, simply add ".png" in the line with the icon's path, so that this
`Icon=/usr/lib/sharik/assets/icon`
looks like this
`Icon=/usr/lib/sharik/assets/icon.png`
The png file is already there, it is just not used due to this mistake in the path.

For the group issue, simply add it to a group. I assume the network category is good enough for it, so this
`Categories=`
should change to this
`Categories=Network;`

So, after both those changes, the .desktop file looks like so
```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Categories=Network;
Name=sharik
Icon=/usr/lib/sharik/assets/icon.png
Exec=/usr/lib/sharik/sharik
```
and looks like this in the menu.

![2021-01-20-182458_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/105204537-f4584600-5b4c-11eb-88c3-7b87a16cd131.png)

**Comment by marchellodev** [comment]
Cool, thanks!
