### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by Batcastle** [marchellodev/sharik#31]
Hey!

I'm using Sharik on Android 10. I was wondering if it would be possible to add a dark mode in the future? I tried enabling "Force Dark Mode" in the Developer settings and it didn't change Sharik to be dark mode. Hoping a first party solution is possible in the future. 

Thanks!

**Comment by marchellodev** [comment]
Thanks! A lot of people have asked me this improvement, I am going to implement dark theme in Sharik v3 with a few other improvements

**Comment by marchellodev** [comment]
This is implemented in Sharik v3 https://github.com/marchellodev/sharik/issues/63 !

Thank you for the suggestion, I'll close this issue for now.
