### ISSUE TITLE
App icon not showing in linux (ubuntu 20.04.2)

### ISSUE THREAD

**Issue by nikunjkumarnakum** [marchellodev/sharik#45]
App icon is not showing in Ubuntu 20.04.2 but i can open app it's a short of bug. I tried reinstalling but no use.

**Comment by marchellodev** [comment]
Hey,

How exactly did you install it? Was it a deb file, snap, something else?

**Comment by nikunjkumarnakum** [comment]
I installed a deb file (sharik_v2.5_linux.deb) from github releses.

**Comment by marchellodev** [comment]
Thanks!

I'll look into it soon

**Comment by pitsi** [comment]
The 2 month late answer...
Maybe it is because of the "faulty" .desktop file as I have described here
https://github.com/marchellodev/sharik/issues/27

**Comment by marchellodev** [comment]
Yep, sorry :)

The v3 (which I hope to release very soon) will have a new desktop implementation, so this issue will probably be fixed.

Thanks!
