### ISSUE TITLE
not working in my chromebook(chrome os 88) android. it can send but can't receive.

### ISSUE THREAD

**Issue by BryanMaker** [marchellodev/sharik#46]
It calls the chrome os local file manager when sending files, so that it can easily send chrome os, android, linux files. This is awesome. However, it cannot receive any content. Are you planning to make it work in a chromebook?

**Comment by marchellodev** [comment]
Hey, sorry I didn't respond earlier. Are you talking about the receiver feature?

**Comment by marchellodev** [comment]
I have completely rewritten the receiver, so I believe this issue should be fixed is Sharik v3. Can you please verify? https://github.com/marchellodev/sharik/issues/63

I'll close this issue for now
