### ISSUE TITLE
Cannot use sharik with configserver firewall

### ISSUE THREAD

**Issue by naDevi** [marchellodev/sharik#48]
https://www.configserver.com/cp/csf.html
https://download.configserver.com/csf/install.txt

the firewall manage using csf command for basic control then i have added both PCs IPs to allow list using sudo csf - a 192.168.xx.xxx (it means then i dont need to open ports etc manually or network wide)

I installed sharik on both ubuntu 20.04.02 and 20.04.10 devices but both devices doesn't recognize each other.
![image](https://user-images.githubusercontent.com/73974196/111171359-7017c180-85d7-11eb-98a7-2f24fc79e69f.png)

If i shared a file or text and open link on another device web-browser ofcourse then able to see text or download

These apps works properly
https://snapcraft.io/barrier
https://feem.io/ (it's blazing fast sharing app too)

@marchellodev

**Comment by naDevi** [comment]
This's not a issue; i have misunderstood how sharik work (above mentioned undefined issues seems misleading) just when tap on download button on bottom then receive file well.

**Comment by marchellodev** [comment]
Glad the issue got resolved!
