### ISSUE TITLE
Receiver stuck on progress bar

### ISSUE THREAD

**Issue by frysztak** [marchellodev/sharik#53]
hi there!

after clicking "receiver", all I can see is a modal with a spinner. I left it running for a minute or two but nothing happened. I don't know if it's relevant, but spinner is kind of choppy (I'm thinking either some work is being done in UI thread or it's a quirk of Flutter). sending files from my phone to PC works.

**Comment by marchellodev** [comment]
Yeah, the spinner indicates that the app is scanning devices in the local network looking for another sharik sharing files

I guess we should explain more explicitly what is going on in the modal window.

Does that answer your question?

Thanks!

**Comment by frysztak** [comment]
yep, it does. I forgot to launch it on my pc. oops...

thanks!
