### ISSUE TITLE
Landscape mode on start and share screen

### ISSUE THREAD

**Issue by Thewisem** [marchellodev/sharik#55]
I would like for you to implement landscape mode as I am using a tablet and it is somewhat annoying to have to go to portrait mode instead of landscape.

**Comment by marchellodev** [comment]
Thanks for the idea!
I hope to make Sharik v3 more adaptive and usable on different screens in general, so I'll do my best to implement this feature :)

**Comment by marchellodev** [comment]
This is implemented in Sharik v3 https://github.com/marchellodev/sharik/issues/63 !

Thank you for the suggestion, I'll close this issue for now.
