### ISSUE TITLE
sharik does not have option in 'share via' android feature 

### ISSUE THREAD

**Issue by fikrillah** [marchellodev/sharik#59]
I don't think I could explain this well, so i think i'll just explain my use case. 

So i want to send a file from a file manager (in my case, i use https://github.com/zhanghai/MaterialFiles). I use share option on the file 

![Screenshot_20210602_025008](https://user-images.githubusercontent.com/48489341/120382784-4789a300-c34e-11eb-9b72-8f80946f7d39.jpg)

But i couldn't find option to share the file with sharik

![Screenshot_20210602_024648](https://user-images.githubusercontent.com/48489341/120382989-83246d00-c34e-11eb-9513-735d05a80fa9.jpg)

It would be nice if i have option to directly send a file from file manager. It's kinda tedious to exit a file manager, open the sharik app and find that same file. 

Thanks for the awesome app btw, keep the great work!!

**Comment by marchellodev** [comment]
Thanks for creating the issue!

I had the same idea some time ago too :). I don't think this feature will be hard to implement, so I hope to add it into v3 (which will be released very very soon :))

Thanks again! I'll keep you updated

**Comment by fikrillah** [comment]
That is nice to hear. 

Considering how well made this app is, i believe you already considered this feature. But i opened this issue anyway just to make sure.

Also, it's an offtopic question, my default browser is firefox on my android phone. It seems like firefox can't use the proper name of the file i'm transfering. That might be a firefox issue, but, are you planning to have built-in downloader to avoid this issue? Or do you have something else in mind?

**Comment by marchellodev** [comment]
Built-in downloader is a good idea, thanks

It's probably not the issue with firefox. What kind of file did you share and what was the name of it?

**Comment by fikrillah** [comment]
For exame 'test file.txt' would be 'test%20file.txt' with firefox. I don't find this issue with opera. I'm sure other android browser don't have this issue.

**Comment by marchellodev** [comment]
Ok, I'll look into it, thanks!

**Comment by fikrillah** [comment]
Nice!

**Comment by marchellodev** [comment]
This is implemented in Sharik v3 https://github.com/marchellodev/sharik/issues/63 !

Thank you for the suggestion, I'll close this issue for now.
