### ISSUE TITLE
Unable to launch desktop app

### ISSUE THREAD

**Issue by Gausoft** [marchellodev/sharik#6]
Nice app!
After installing it on ubuntu 16.04 LTS I got first a system error. After that the app closes if I launch IT

**Comment by marchellodev** [comment]
Yeah, it's a known issue, sharik was built on a "too new system" so currently it can't run on something that old.
I will update the latest release files regarding this issue soon, but for now you can just use the latest AppImage from GitHub releases page, it was build and tested exactly on this system. Or, if you crusially need deb, you can build it for yourself!

Thanks for reporting.

**Comment by Gausoft** [comment]
ok cool
