### ISSUE TITLE
[Feature Request] Adding "Share via Sharik" to the Android sharing menu

### ISSUE THREAD

**Issue by skarpheta** [marchellodev/sharik#66]
I love Sharik but I think It is a simple yet important feature to add to it.

It maybe look like this:
![Screenshot_20210622_161638_com huawei android internal app](https://user-images.githubusercontent.com/42360077/122932424-63dd9600-d376-11eb-95e5-3580e151594c.jpg)

**Comment by marchellodev** [comment]
Duplicate of #59. This is already implemented in v3 (which I hope will be released within the next few days). You can try out this feature now by downloading apk attached to the first post of #63. Feedback is appreciated!

Thanks for the suggestion!

**Comment by marchellodev** [comment]
Also, it seems that you are using a language that is not yet present in Sharik. Would you mind translating the app to it please? @skarpheta 

Tell me what language that is so that I can add it to the crowdin (https://crowdin.com/project/sharik)

**Comment by skarpheta** [comment]
It's actually Turkish and I think it's completely translated but I'll check it out after new updates in case it needs more translation
