### ISSUE TITLE
[Bug?] Navbar is not dark when dark mode is enabled in v3.0

### ISSUE THREAD

**Issue by skarpheta** [marchellodev/sharik#67]
**Device:** Huawei Y6 2019 (MRD-LX1)
**Android version:** 9
**App version:** v3.0

**To reproduce the bug:**
1. Open the app
2. Enable dark mode

**Bug:**
tbh I'm not sure if it's a bug but navigation bar is not dark when dark mode is on. It looks like this:
![Screenshot_20210622_225643_dev marchello sharik (1)](https://user-images.githubusercontent.com/42360077/122991202-6e675200-d3ad-11eb-9d11-c8dff72e61b3.jpg)

**Comment by marchellodev** [comment]
Can you please make a screenshot of how the status bar is changed in other apps in dark mode?

**Comment by skarpheta** [comment]
here it is
![screenshots](https://user-images.githubusercontent.com/42360077/123068790-e3bd3c00-d41a-11eb-9b9f-74c7e3c0048f.jpeg)

**Comment by marchellodev** [comment]
In Sharik, the status bar is dark though, similar to bromite and whatsapp. I don't really understand the problem :)

**Comment by skarpheta** [comment]
yeah, you're right but i was actually talking about navigation bar, not status bar.

**Comment by marchellodev** [comment]
Oh, got it, sorry :)

**Comment by marchellodev** [comment]
Done. This is how it looks now (regardless of the selected theme)

![image](https://user-images.githubusercontent.com/61112084/123079555-bbd2d600-d424-11eb-9462-561872c5d8f3.png)


Thank you for the report!
