### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by mrfoxie** [marchellodev/sharik#7]
Is there any way to add more language

**Comment by marchellodev** [comment]
Yes, there is a tutorial on how to do so in the readme:

If you want to help with translation, create a fork of this repo, add file lib/locales/<Your language>.dart with your translation and submit pull request.

If that's too complicated for you, take a look at lib/locales/ru.dart or lib/locales/ua.dart, create a similar file for your language and send it to me (via email or open an issue). 


If you have any problems, let me know.

**Comment by mrfoxie** [comment]
let me try

**Comment by marchellodev** [comment]
@mrfoxie Hi, any news?

**Comment by mrfoxie** [comment]
yes I'm still adding more languages but it will take more time this is all Indian languages so I'm removing others and adding all Indian languages

**Comment by mrfoxie** [comment]
> @mrfoxie Hi, any news?

sorry bro for late reply I was been busy in university exams for my last semester I will be adding more languages.

**Comment by mrfoxie** [comment]
hello I have added 2 more languages and created pull request if you want to add more languages then tell me I will add it and create a pull request

**Comment by marchellodev** [comment]
@mrfoxie That's very cool, thank you for this contribution. I'll merge the pull request and release a new version as soon as possible!

I'm not insisting, but if you can add more languages and feel like it, It would be great to have more locales in this app. This application's code is open, everyone can contribute to it how much they want.

**Comment by mrfoxie** [comment]
if you don't mind can I add more colour and material design like testing so that you can like it

**Comment by marchellodev** [comment]
@mrfoxie Yeah, you can try and we'll see how it goes.
Although, it would be a bit better if you created a sketch in figma or photoshop of your improvement and shared with me, so we can discuss the proposal in detail first.

**Comment by mrfoxie** [comment]
sure and can I ask you that where did you learn this flutter? it's on you if you want to answer or else it's okay.

**Comment by marchellodev** [comment]
@mrfoxie The official website and documentation are pretty good in terms of learning the framework. So I'd recommend you to start with [flutter.dev](https://flutter.dev).

Also I'd recommend their YouTube channel, especially those playlists:
[https://www.youtube.com/playlist?list=PLjxrf2q8roU23XGwz3Km7sQZFTdB996iG](https://www.youtube.com/playlist?list=PLjxrf2q8roU23XGwz3Km7sQZFTdB996iG)

[https://www.youtube.com/playlist?list=PLjxrf2q8roU3ahJVrSgAnPjzkpGmL9Czl](https://www.youtube.com/playlist?list=PLjxrf2q8roU3ahJVrSgAnPjzkpGmL9Czl)

But I'm sure there are a lot of resources on Hindi as well. In fact Indian community is one of the biggest when in comes to flutter.

Flutter is an awesome framework for software development. It's very powerful and easy to learn, it's always a great idea to have something like that in a toolset.

If you have any questions or troubles during your learning process, fell free to email me, I'd love to help!

**Comment by mrfoxie** [comment]
> @mrfoxie Yeah, you can try and we'll see how it goes.
> Although, it would be a bit better if you created a sketch in figma or photoshop of your improvement and shared with me, so we can discuss the proposal in detail first.

I will be using adobe xd so it can be easily export to flutter when it is done I will share you as soon as possible and after that, I have 2 suggestion for you so that it can help you for more sharing it with interactive with people

**Comment by marchellodev** [comment]
@mrfoxie Cool, but if you are going to use plugin for transferring xd design to flutter code, please make sure that your code is readable, nice and efficient.

Good luck!

**Comment by mrfoxie** [comment]
yes sure

**Comment by mrfoxie** [comment]
> @mrfoxie Cool, but if you are going to use plugin for transferring xd design to flutter code, please make sure that your code is readable, nice and efficient.
> 
> Good luck!

hey bro can you check this link and tell me any changes are too been made [Sharik - concept](https://xd.adobe.com/view/1b435fda-7f45-458a-a7d4-3d6fdfe8c16c-4e10/) I have put my logo in the but I will make your logo in photoshop again and rechange the color

**Comment by marchellodev** [comment]
@mrfoxie Hi!
Well, first of all, I'm very happy to see your genuine interest in this project. You concept is very interesting, but unfortunately, it is not consistent with my view. For this application I would prefer to have a simple clean design, without any shadows or "heavy" colors.
Your version is very nice, but I just won't be able to accept such pull request.
However, you can create a fork of this project and create your own version of sharik!
For example, there is another [sharik out there](https://play.google.com/store/apps/details?id=dev.alkhalaf.sharik) with completely different design.

But if you still want to specifically contribute to this project, you should follow sharik's style. Dark mode seems like a really nice addition, but once again, it should be consistent with the current version of the app.

Speaking of the sharik's logo, here is the a figma workspace, you can take it from here, as well as some other components. But it is just a mockup, sharik now is quite different in terms of design.

[Figma](https://www.figma.com/file/wKQ3UtPTcJ0la88ZnmFFyl/Untitled)

**Comment by mrfoxie** [comment]
as I mentioned earlier I'm not a flutter developer but i will clone your repo and try to make changes in it and check whether it is working or not and for the images they are all svg and I will try to do as you said if any problems occurs then I will contact you.

**Comment by mrfoxie** [comment]
> @mrfoxie Hi!
> Well, first of all, I'm very happy to see your genuine interest in this project. You concept is very interesting, but unfortunately, it is not consistent with my view. For this application I would prefer to have a simple clean design, without any shadows or "heavy" colors.
> Your version is very nice, but I just won't be able to accept such pull request.
> However, you can create a fork of this project and create your own version of sharik!
> For example, there is another [sharik out there](https://play.google.com/store/apps/details?id=dev.alkhalaf.sharik) with completely different design.
> 
> But if you still want to specifically contribute to this project, you should follow sharik's style. Dark mode seems like a really nice addition, but once again, it should be consistent with the current version of the app.
> 
> Speaking of the sharik's logo, here is the a figma workspace, you can take it from here, as well as some other components. But it is just a mockup, sharik now is quite different in terms of design.
> 
> [Figma](https://www.figma.com/file/wKQ3UtPTcJ0la88ZnmFFyl/Untitled)

bro I have a question I have changed to figma studio as you mentioned that you need a simple and clear design so I was thinking of adding clear photos on intro screen and other and one more thing is the background for dark is okay or not.

**Comment by marchellodev** [comment]
Dark theme is ok, speaking of photos I don't really understand what you mean

**Comment by mrfoxie** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/25217451/89733574-f08ba800-da73-11ea-82a7-2abdd22f088c.png)
the circle in the screen shot above

**Comment by marchellodev** [comment]
This seems to be ok

**Comment by mrfoxie** [comment]
bro, I clone your repo and tried to run it on my device but is not debugging and it's giving me this error
![image](https://user-images.githubusercontent.com/25217451/89772760-3aca6300-db20-11ea-9e3b-bde0cabe8850.png)

**Comment by marchellodev** [comment]
That's weird.
You may also install [hover](https://hover.build) and try to run this app directly on widows.

**Comment by mrfoxie** [comment]
> That's weird.
> You may also install [hover](https://hover.build) and try to run this app directly on widows.

okay [sharik-concept ](https://www.figma.com/file/NfQkNHcncZD4ilsWe37qaY/Sharik?node-id=0%3A1) check this I have invited you there

**Comment by marchellodev** [comment]
You didn't have to use figma specifically :)
In addition, I didn't receive an invite on my email `marchellodev@gmail.com`, where is it?

**Comment by marchellodev** [comment]
Nevermind, I have the invitation

**Comment by marchellodev** [comment]
This one  is a bit better, but there is still a significant lack of consistency. I left my comment in the figma workspace

**Comment by mrfoxie** [comment]
okay
