### ISSUE TITLE
v3.0 has lower version code then v2.5

### ISSUE THREAD

**Issue by jspricke** [marchellodev/sharik#84]
v2.5 has versionCode 10:
https://github.com/marchellodev/sharik/commit/2ae502d553fbf5c1c47e127f9254ddea176e6ba0#diff-9526ccfd1d1813ed49c39f8c54dbeb512607376a007d824b905bc8b4e4d202d9L50

whereas v3.0 has versionCode 8:
https://github.com/marchellodev/sharik/blob/8c06d1446b4da7fcdc6bc93459fe9116630beac7/pubspec.yaml#L8

This is not allowed in Android and the system refuses an upgrade. Due to this the Sharik version on F-Droid is still 2.5. Could you bump the version code to higher then 10 and tag a new version? Thanks!

**Comment by marchellodev** [comment]
Thanks! I have just created a new tag. Does this solve the issue?

**Comment by jspricke** [comment]
Depends, normally flutter apps define the version code in `pubspec.yaml`, whereas you did it in the gradle file now. Is that on purpose?

**Comment by marchellodev** [comment]
Yeah, it's a temporary solution. For the next release, I will research how the `flutterVersionCode.toInteger()` and `flutterVersionName` work and base future gradle files on these functions instead.

**Comment by jspricke** [comment]
Why not simply bump the version in the `pubspec.yaml`

**Comment by marchellodev** [comment]
Oh, right, I have just noticed that I could do just that. lol, my bad, sorry. That will work though, right?

**Comment by jspricke** [comment]
yes :+1:

**Comment by jspricke** [comment]
Do you still push a new tag?

**Comment by marchellodev** [comment]
Is there a need for it?

**Comment by jspricke** [comment]
F-Droid would automatically find and build that version without me fixing things ;).

**Comment by marchellodev** [comment]
Cool, thanks for opening the issue!

**Comment by jspricke** [comment]
so will you push a tag or should I do stuff manually?

**Comment by marchellodev** [comment]
Sorry, what do you mean by pushing a tag? :>

**Comment by jspricke** [comment]
A new tag where the `pubspec.yaml` has a higher version code

**Comment by marchellodev** [comment]
Done https://github.com/marchellodev/sharik/blob/v3.0.1/pubspec.yaml

Do I also need to create a new release on Github?

**Comment by jspricke** [comment]
Works for me now, thanks!
