### ISSUE TITLE
how to complie for linux for ver 3.1? thx

### ISSUE THREAD

**Issue by kocoman1** [marchellodev/sharik#96]
how to complie for linux for ver 3.1? thx

**Comment by marchellodev** [comment]
From the Flutter website:

![image](https://user-images.githubusercontent.com/61112084/128700189-05eca4e5-8c7b-432b-8316-ae1094d3cd13.png)


So it seems like Debian 10 (Linux 4.19) and above is supported. I'm going to try running and building the app on Ubuntu 11.10 (Linux 3.0.0-12-generic). I'll keep you updated

Also, if you don't mind me asking, why do you need this app working on such an old system? :)

**Comment by kocoman1** [comment]
i mean sharik ver 3.1 not kernel 3.1.. want to look at folder sending

**Comment by marchellodev** [comment]
1. Install flutter https://flutter.dev/docs/get-started/install
2. Install android studio (if you need android) https://developer.android.com/studio
3. Enable beta desktop support (https://flutter.dev/desktop)
3. Clone the repository
4. Run `flutter build apk --split-per-abi` or `flutter build windows` or `flutter build linux`

Also, I can build it for you if you want to :). What platform do you need?

**Comment by marchellodev** [comment]
Oh, I've just realized that you are interested in linux, sorry :) I have attached the binary below. Just extract the archive and run the `sharik` file. Please let me know if you run into any issues with the new version!

[bundle.zip](https://github.com/marchellodev/sharik/files/6957414/bundle.zip)
