### ISSUE TITLE
[Not a bug but] After the update, Sharik is lagging in some situations

### ISSUE THREAD

**Issue by dybdeskarphet** [marchellodev/sharik#97]
**Phone:** MRD-LX1 (Huawei Y6 2019)
**Android version:** 9.0
**App version:** 3.0.0

**Problem:** After the update, when I click on the send button, the app is lagging really bad probably because of the blur. I was going to ask if you may consider deleting blur but my phone is low-end so I'd totally understand if you won't consider.

Here is a video if helps: https://youtu.be/gyYp-xONcpg

**Comment by marchellodev** [comment]
Thanks for the video!

Can you please check if the same happens with other dialog screens? Receiver, tracking policy, and privacy policy

**Comment by skarpheta** [comment]
Yup, it is happening on those dialogs too: https://youtu.be/V80QEu3cDXs

**Comment by marchellodev** [comment]
Can you please remove the version from f-droid and install the one I attached to this post? I have disabled blur and page transitioning effect. I have tested it a bit, and it seems to work a bit faster. If this really works much better, we could have it as an option in the settings screen.

Thanks!

[app-arm64-v8a-release.zip](https://github.com/marchellodev/sharik/files/6960921/app-arm64-v8a-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/marchellodev/sharik/files/6960922/app-armeabi-v7a-release.zip)
[app-x86_64-release.zip](https://github.com/marchellodev/sharik/files/6960923/app-x86_64-release.zip)

**Comment by skarpheta** [comment]
I was going to try to do it myself but apparently Sharik is written in Dart and I don't know Dart. Thank you so so much, you're the most helpful developer i've ever seen.

**Comment by skarpheta** [comment]
Yeah sure: https://www.youtube.com/watch?v=Kzt1-biOyb4 There is a real difference I think
